# Generated by Django 6.0.3 on 2026-03-30 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category2',
        ),
    ]
