# Generated by Django 6.0.3 on 2026-04-01 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_pop'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pop',
            new_name='Rock',
        ),
    ]
