# Generated by Django 6.0.3 on 2026-04-02 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_rename_pop_rock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('audio', models.FileField(blank=True, null=True, upload_to='audio/')),
            ],
        ),
    ]
