# Generated by Django 6.0.3 on 2026-04-02 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0006_anison_ballad_children_country_hiprap_in_un_j_pop_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Country',
            new_name='Co_dien',
        ),
    ]
