# Generated by Django 6.0.3 on 2026-04-02 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0007_rename_country_co_dien'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Children',
            new_name='Thieu_nhi',
        ),
    ]
