# Generated by Django 6.0.3 on 2026-04-02 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0008_rename_children_thieu_nhi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Downloaded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('audio', models.FileField(upload_to='downloads/')),
                ('date_downloaded', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
