# Generated by Django 6.0.3 on 2026-04-03 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0009_downloaded'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Downloaded',
        ),
    ]
