# Generated by Django 6.0.3 on 2026-04-01 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_musichot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category/'),
        ),
        migrations.AlterField(
            model_name='musichot',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='rock/'),
        ),
    ]
