# Generated by Django 6.0.3 on 2026-04-05 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exclusive', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exclusiveitem',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='exclusive/audio/'),
        ),
    ]
