# Generated by Django 6.0.3 on 2026-04-03 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kho', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermusic',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='usermusic',
            name='audio',
            field=models.FileField(upload_to='kho/'),
        ),
    ]
