# Generated by Django 6.0.3 on 2026-04-03 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kho', '0002_usermusic_image_alter_usermusic_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermusic',
            name='source_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
