# Generated by Django 6.0.3 on 2026-04-03 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kho', '0003_usermusic_source_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermusic',
            name='source_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
